version: 2
updates:
  - package-ecosystem: "gomod"
    vendor: true
    directory: /
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
      timezone: "UTC"
    commit-message:
      prefix: "some/prefix"
    groups:
      all-updates:
        patterns:
          - "*"
    open-pull-requests-limit: 1
    pull-request-branch-name:
        separator: "-"
    reviewers:
      - "my-git-uname"
